#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "pandas>=3.0.2",
#     "pyvista>=0.47.3",
# ]
# ///
import pandas as pd
import numpy as np
import pyvista as pv
import math
import random

# We can choose this constant to make the FlatMesh look more or less low-poly
nb_points = 100

# Find the radius of nb_points packed circles from www.packomania.com
radius_table = pd.read_csv("http://hydra.nat.uni-magdeburg.de/packing/cci/txt/radius.txt", header=None, sep=' ')
radius = float(radius_table.loc[radius_table[0] == nb_points, 1].iloc[0])

# Download the coordinates of nb_points optimally packed circles
points = pd.read_csv("http://hydra.nat.uni-magdeburg.de/packing/cci/txt/cci" + str(nb_points) + ".txt", sep=' ',
        skipinitialspace=True, header=None).drop(columns=0).to_numpy()

# Import these points as a 3D points cloud in PyVista
cloud = pv.PolyData(np.hstack((points, np.zeros((points.shape[0], 1)))))

# Generate a Delaunay triangulation of this points cloud
mesh = cloud.delaunay_2d()

# === CHANGED: Get triangles directly instead of strips ===
# PyVista/VTK stores faces as [n0, i0, i1, i2, n1, i3, i4, i5, ...]
# where n is the number of points in the face (3 for triangles)
faces = mesh.faces.reshape(-1, 4)[:, 1:]  # Drop the count column, keep only vertex indices

# Each vertex is represented as a tuple of: x, y (its base coordinates) and a color mixing ratio
vertices = []
indices = []

# Each vertex is represented as a tuple of: x, y (its base coordinates, before any shift) and a color mixing ratio
def add_vertex(index, mix=None):
    x, y = points[index]

    # Re-use existing vertices as much as possible
    for i, vertex in enumerate(vertices):
        if vertex[0] == x and vertex[1] == y:
            if vertex[2] is None:
                vertices[i] = (x, y, mix)
            if vertices[i][2] == mix or mix is None:
                indices.append(i)
                return
    # Create a new vertex if no match found
    indices.append(len(vertices))
    vertices.append((x, y, mix))

# The color mixing ratio depends on the distance of triangle's barycenter to the center
def triangle_color_mix(index0, index1, index2):
    x0, y0 = points[index0]
    x1, y1 = points[index1]
    x2, y2 = points[index2]
    x = (x0+x1+x2)/3
    y = (y0+y1+y2)/3
    distance_to_center = math.sqrt(x**2 + y**2) * 1.2
    mix = distance_to_center**1.7
    return min(mix, 1.0)

# === CHANGED: Iterate over triangles directly, not strips ===
for triangle in faces:
    i0, i1, i2 = triangle
    mix = triangle_color_mix(i0, i1, i2)
    # Add all 3 vertices of the triangle with the same mix value
    add_vertex(i0, mix)
    add_vertex(i1, mix)
    add_vertex(i2, mix)

# Generate a C++ header that contains the vertices/indices/shifts
out = open("flatmeshgeometry.h", "w")
out.write("// Do not modify manually! This file is generated by generate_flatmeshgeometry.py\n\n")

# Output the vertices and their color mix attribute
out.write("static const QVector3D flatmesh_vertices[] = {\n")
for vertex in vertices:
    x = vertex[0]
    y = vertex[1]
    mix = vertex[2] if vertex[2] is not None else 0.0
    out.write(f"    QVector3D({x/2}, {y/2}, {mix}),\n")
out.write("};\n")
out.write(f"static const int flatmesh_vertices_sz = {len(vertices)};\n\n")

# Output the indices (now already in triangle list format, no strips)
out.write("static const unsigned short flatmesh_indices[] = {\n")
for index in indices:
    out.write(f"    {index},\n")
out.write("};\n")
out.write(f"static const int flatmesh_indices_sz = {len(indices)};\n\n")

# Pre-calculate random shifts
random_shifts_nb = 128
out.write("static const float flatmesh_shifts[] = {\n")
for i in range(random_shifts_nb):
    r = radius * math.sqrt(random.random())
    alpha = 2 * math.pi * random.random()
    x = r * math.cos(alpha) * 0.8
    y = r * math.sin(alpha) * 0.8
    out.write(f"    {x/2}, {y/2},\n")
out.write("};\n")
out.write(f"static const int flatmesh_shifts_nb = {random_shifts_nb};\n")
out.write(f"#define FLATMESH_SHIFTS_NB_STR \"{random_shifts_nb}\"")

out.close()

# Output statistics
vertices_bytes = len(vertices)*(2*4+3)
print(f"{len(vertices)} vertices take {vertices_bytes} bytes")
indices_bytes = len(indices)*2
print(f"{len(indices)} indices take {indices_bytes} bytes")
shifts_bytes = random_shifts_nb*2*4
print(f"{random_shifts_nb} shifts take {shifts_bytes} bytes")
print(f"Total takes {vertices_bytes+indices_bytes+shifts_bytes} bytes")